apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-ifue
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-mydu-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-ifue@sha256:983810b0601c739e5c2924087b3ff26fd26c229825d1813672027da81c3ea444
        name: my-python
        resources: {}
status: {}
